// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-grpc-todo/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-grpc-todo/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{1}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	User                 *User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message              *common.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{2}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResponse) GetMessage() *common.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UserRegisterRequest struct {
	User                 *User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string          `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Message              *common.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{3}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterRequest) GetMessage() *common.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UserRegisterResponse struct {
	User                 *User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message              *common.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{4}
}

func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserRegisterResponse) GetMessage() *common.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UserUpdateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRequest) Reset()         { *m = UserUpdateRequest{} }
func (m *UserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRequest) ProtoMessage()    {}
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{5}
}

func (m *UserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRequest.Unmarshal(m, b)
}
func (m *UserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRequest.Merge(m, src)
}
func (m *UserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRequest.Size(m)
}
func (m *UserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRequest proto.InternalMessageInfo

func (m *UserUpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateResponse struct {
	User                 *User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message              *common.Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserUpdateResponse) Reset()         { *m = UserUpdateResponse{} }
func (m *UserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResponse) ProtoMessage()    {}
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b8cb181af0625e, []int{6}
}

func (m *UserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResponse.Unmarshal(m, b)
}
func (m *UserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResponse.Merge(m, src)
}
func (m *UserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResponse.Size(m)
}
func (m *UserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResponse proto.InternalMessageInfo

func (m *UserUpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserUpdateResponse) GetMessage() *common.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserLoginRequest)(nil), "UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "UserLoginResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "UserRegisterResponse")
	proto.RegisterType((*UserUpdateRequest)(nil), "UserUpdateRequest")
	proto.RegisterType((*UserUpdateResponse)(nil), "UserUpdateResponse")
}

func init() { proto.RegisterFile("go-grpc-todo/user/user.proto", fileDescriptor_72b8cb181af0625e) }

var fileDescriptor_72b8cb181af0625e = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0x11, 0xb0, 0x0e, 0x17, 0x19, 0x30, 0xc1, 0x8d, 0x07, 0xdd, 0x93, 0x17, 0x96, 0x88,
	0x07, 0x3f, 0xc0, 0x83, 0x89, 0xc1, 0xc4, 0xd4, 0xf0, 0x01, 0x95, 0x4e, 0x6a, 0x83, 0xed, 0xae,
	0xdd, 0x25, 0xfe, 0x91, 0xdf, 0x69, 0x76, 0x97, 0x9a, 0x16, 0x10, 0xbc, 0x78, 0x69, 0xfb, 0x66,
	0x66, 0xdf, 0xbc, 0x37, 0xd3, 0x85, 0x8b, 0x54, 0x8e, 0xd3, 0x52, 0x2d, 0xc6, 0x46, 0x26, 0x72,
	0xb2, 0xd2, 0x54, 0xba, 0x87, 0x50, 0xa5, 0x34, 0x92, 0x5d, 0x35, 0xb2, 0x0b, 0x99, 0xe7, 0xb2,
	0x98, 0xe4, 0xa4, 0x75, 0x9c, 0x92, 0x2f, 0xe1, 0x33, 0x68, 0xcf, 0x35, 0x95, 0x88, 0xd0, 0x2e,
	0xe2, 0x9c, 0x46, 0xc1, 0x65, 0x70, 0x7d, 0x12, 0xb9, 0x6f, 0x64, 0x10, 0x5a, 0x32, 0x17, 0x6f,
	0xb9, 0xf8, 0x0f, 0xc6, 0x21, 0x74, 0x28, 0x8f, 0xb3, 0xf7, 0xd1, 0x91, 0x4b, 0x78, 0xc0, 0x1f,
	0xe1, 0xd4, 0xb2, 0xcd, 0x64, 0x9a, 0x15, 0x11, 0x7d, 0xac, 0x48, 0x9b, 0x06, 0x4b, 0xb0, 0xc1,
	0xc2, 0x20, 0x54, 0xb1, 0xd6, 0x9f, 0xb2, 0x4c, 0xaa, 0x0e, 0x15, 0xe6, 0x6f, 0xd0, 0xaf, 0x71,
	0x69, 0x25, 0x0b, 0x4d, 0x78, 0x0e, 0x6d, 0x7b, 0xd8, 0x11, 0xf5, 0xa6, 0x1d, 0x61, 0x2b, 0x22,
	0x17, 0xb2, 0x8a, 0x8c, 0x5c, 0x52, 0xb1, 0x26, 0xf2, 0x00, 0x39, 0x1c, 0xaf, 0x0d, 0x3b, 0xa5,
	0xbd, 0x69, 0x28, 0x9e, 0x3c, 0x8e, 0xaa, 0x04, 0x57, 0x30, 0x70, 0x3c, 0x94, 0x66, 0xda, 0xd8,
	0xb7, 0x17, 0xbe, 0xa7, 0xd7, 0x1e, 0xdd, 0x7f, 0xea, 0xb8, 0x84, 0x61, 0xb3, 0xe3, 0x7f, 0xda,
	0x13, 0x7e, 0x90, 0x73, 0x95, 0xc4, 0x86, 0x0e, 0x9b, 0xe3, 0x2f, 0x80, 0xf5, 0xfa, 0xc3, 0xd2,
	0x6a, 0x22, 0x5a, 0xbf, 0x88, 0x98, 0x7e, 0x05, 0x10, 0xda, 0x23, 0x0f, 0xd1, 0xf3, 0x3d, 0x0a,
	0xe8, 0xb8, 0xb5, 0x62, 0x5f, 0x6c, 0xfe, 0x2e, 0x0c, 0xc5, 0xf6, 0xd6, 0xef, 0x20, 0xac, 0x46,
	0x85, 0x43, 0xb1, 0x63, 0x57, 0xec, 0x4c, 0xec, 0x9c, 0xe7, 0x0d, 0x74, 0xbd, 0x0d, 0xf4, 0xb4,
	0x8d, 0x19, 0xb0, 0x81, 0xd8, 0xf6, 0xf9, 0xda, 0x75, 0xf7, 0xe2, 0xf6, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x46, 0x28, 0xd5, 0xe0, 0x5a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserGRPCClient is the client API for UserGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserGRPCClient interface {
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
	Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error)
}

type userGRPCClient struct {
	cc *grpc.ClientConn
}

func NewUserGRPCClient(cc *grpc.ClientConn) UserGRPCClient {
	return &userGRPCClient{cc}
}

func (c *userGRPCClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, "/UserGRPC/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCClient) Register(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	out := new(UserRegisterResponse)
	err := c.cc.Invoke(ctx, "/UserGRPC/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGRPCClient) Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error) {
	out := new(UserUpdateResponse)
	err := c.cc.Invoke(ctx, "/UserGRPC/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGRPCServer is the server API for UserGRPC service.
type UserGRPCServer interface {
	Login(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	Register(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	Update(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error)
}

// UnimplementedUserGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedUserGRPCServer struct {
}

func (*UnimplementedUserGRPCServer) Login(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserGRPCServer) Register(ctx context.Context, req *UserRegisterRequest) (*UserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserGRPCServer) Update(ctx context.Context, req *UserUpdateRequest) (*UserUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterUserGRPCServer(s *grpc.Server, srv UserGRPCServer) {
	s.RegisterService(&_UserGRPC_serviceDesc, srv)
}

func _UserGRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserGRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPC_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserGRPC/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCServer).Register(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGRPC_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGRPCServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserGRPC/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGRPCServer).Update(ctx, req.(*UserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserGRPC",
	HandlerType: (*UserGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserGRPC_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserGRPC_Register_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserGRPC_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-grpc-todo/user/user.proto",
}
